name: Build Provisioning Service

on:
  push:
    branches:
      - live
    paths:
      - "services/provisioning-service/**"
      - ".github/workflows/provisioning-service.yml"

# This permission is required for GHCR to write packages
permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Fix Capital Letters (Standard "Hack" for GHCR)
      - name: Lowercase Repo Owner
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
        env:
          GITHUB_REPOSITORY_OWNER: "${{ github.repository_owner }}"

      # 3. Build and Push (Use env.REPO_OWNER now)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/provisioning-service
          file: ./services/provisioning-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/provisioning-service:latest
            ghcr.io/${{ env.REPO_OWNER }}/provisioning-service:${{ github.sha }}

      # # 4. Trigger Render
      # - name: Trigger Render Deploy
      #   run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_AUTH }}
